<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ModelsTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Discorss.Common\Discorss.Common.fsproj" />
    <ProjectReference Include="..\..\src\Discorss.Ingestion\Discorss.Ingestion.fsproj" />
  </ItemGroup>

</Project>
