
version: '3.4'

services:
  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    networks:
      - discorssnetwork
    ports:
      - "27017:27017"

  microbroker:
    image: "ghcr.io/tonycknight/microbroker:latest"
    depends_on: [mongodb]
    networks:
      - discorssnetwork
    ports:
      - "8080:8080"
    command: '--mongoConnection=mongodb://mongodb:27017 --mongoDbName=microbroker --hostUrls=http://+:8080'

  discorss:
    image: discorss
    networks:
      - discorssnetwork
    ports:
      - "8081:8081"    
    command: '--Discorss:microbrokerServiceUrl=http://microbroker:8080 --Discorss:mongoDbName=discorss --Discorss:mongoConnection=mongodb://mongodb:27017'

networks:
  discorssnetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"