<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="TestHelpers.fs" />
    <None Include="SampleFeeds\MsRss20Feed.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="SampleFeeds\RdfFeed.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="SampleFeeds\Rss091Feed.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="SampleFeeds\Rss092Feed.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="SampleFeeds\Rss20Feed.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Compile Include="Feeds\RdfParserBenchmarks.fs" />
    <Compile Include="Feeds\Rss092ParserBenchmarks.fs" />
    <Compile Include="Feeds\Rss091ParserBenchmarks.fs" />
    <Compile Include="Feeds\Rss20ParserBenchmarks.fs" />
    <Compile Include="Indexing\TokenisationBenchmarks.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Discorss.Common\Discorss.Common.fsproj" />
    <ProjectReference Include="..\..\src\Discorss.Documents\Discorss.Documents.fsproj" />
    <ProjectReference Include="..\..\src\Discorss.Feeds\Discorss.Feeds.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />        
  </ItemGroup>  
</Project>