<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>3391</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>3391</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Models.fs" />
    <Compile Include="Rss.fs" />
    <Compile Include="Rss091Parser.fs" />
    <Compile Include="Rss092Parser.fs" />
    <Compile Include="Rss20Parser.fs" />
    <Compile Include="RdfParser.fs" />
    <Compile Include="AtomParser.fs" />
    <Compile Include="FeedReader.fs" />
    <Compile Include="FeedRepository.fs" />
    <Compile Include="FeedProvider.fs" />
    <Compile Include="Bootstrap.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Discorss.Common\Discorss.Common.fsproj" />
  </ItemGroup>
  
</Project>