<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>3391</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>3391</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Models.fs" />
    <Compile Include="Xml.fs" />
    <Compile Include="Rss.fs" />
    <Compile Include="Rss091Parser.fs" />
    <Compile Include="Rss092Parser.fs" />
    <Compile Include="Rss20Parser.fs" />
    <Compile Include="FeedReader.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Discorss.Common\Discorss.Common.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>