<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models.fs" />
    <Compile Include="DocumentRepository.fs" />
    <Compile Include="DocumentNotificationWriter.fs" />
    <Compile Include="DocumentNotificationReader.fs" />
    <Compile Include="Lexicons.fs" />
    <Compile Include="Tokenisation.fs" />
    <Compile Include="DocumentAnalyser.fs" />
    <Compile Include="Bootstrap.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Discorss.Common\Discorss.Common.fsproj" />
  </ItemGroup>

</Project>
