<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Arbitraries.fs" />
    <Compile Include="TestHelpers.fs" />
    <Compile Include="Feeds\MongoFeedRepositoryTests.fs" />    
    <Compile Include="Documents\MongoDocumentRepositoryTests.fs" />    
    <Compile Include="Documents\MongoDocumentStatisticsRepositoryTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Discorss.Common\Discorss.Common.fsproj" />
    <ProjectReference Include="..\..\src\Discorss.Documents\Discorss.Documents.fsproj" />
    <ProjectReference Include="..\..\src\Discorss.Feeds\Discorss.Feeds.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Feeds\" />
  </ItemGroup>

</Project>