<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LexiconsTests.fs" />
    <Compile Include="BsonMapping.fs" />
    <Compile Include="TokenisationTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Discorss.Documents\Discorss.Documents.fsproj" />
  </ItemGroup>

</Project>