<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="WebAppHandlers.fs" />
    <Compile Include="WebApp.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Discorss.ApiModels\Discorss.ApiModels.fsproj" />
    <ProjectReference Include="..\Discorss.Common\Discorss.Common.fsproj" />
    <ProjectReference Include="..\Discorss.Feeds\Discorss.Feeds.fsproj" />
    <ProjectReference Include="..\Discorss.Indexing\Discorss.Indexing.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Giraffe" Version="8.2.0" />
  </ItemGroup>  
</Project>