<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="HtmlTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Discorss.Common\Discorss.Common.fsproj" />
  </ItemGroup>

  <Import Project="..\..\.paket\Paket.Restore.targets" />

</Project>
