name: Build & Release

permissions:
  actions: read
  pull-requests: write
  security-events: write
  contents: write
  checks: write

on:
  push:
  workflow_dispatch:

env:
  build-version-number: 0.1.${{ github.run_number }}  
  docker-image-server: ghcr.io/tonycknight/discorss
     
jobs:
  sca:
    uses: ./.github/workflows/sca.yml
    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v6
                
      - name: Restore dependencies
        run: |
          dotnet tool restore
          dotnet restore
              
      - name: Build solution
        run: dotnet build -c Release

      - name: Build CLI package 
        run: |
          dotnet pack ./src/Discorss.Cli/Discorss.Cli.fsproj -c Release -o ./package/ -p:PackageVersion=${{ env.build-version-number }}-preview -p:Version=${{ env.build-version-number }}-preview /p:ContinuousIntegrationBuild=true

      - name: Archive CLI package
        uses: actions/upload-artifact@v7
        with:
          name: discorss-cli
          path: |
            ./package/**.nupkg

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v6
                
      - name: Restore dependencies
        run: |
          dotnet tool restore
          dotnet restore
              
      - name: Run Tests
        run: dotnet test -c Debug --filter FullyQualifiedName!~integration /p:CollectCoverage=true /p:CoverletOutput=./TestResults/coverage.info /p:CoverletOutputFormat=cobertura --logger "trx;LogFileName=test_results.trx" 

      - name: Consolidate code coverage
        if: always()
        run: |
          dotnet reportgenerator -reports:"./test/**/coverage.info" -targetdir:"./publish/codecoverage" -reporttypes:"Html"  
          dotnet reportgenerator -reports:"./test/**/coverage.info" -targetdir:"./publish/codecoveragedata" -reporttypes:"Cobertura"
      
      - name: Archive Test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: tests.results
          path: |
            ./test/**/TestResults/*
          
      - name: Archive Code coverage report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: code_coverage_report
          path: ./publish/codecoverage/*.*

      - name: Archive Code coverage
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: codecoverage
          path: ./publish/codecoveragedata/*.*
          
      - name: Unit test results
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: unit test results
          path: ${{ github.workspace }}/test/**/TestResults/test_results.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Code coverage results
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path: ${{ github.workspace }}/publish/codecoveragedata/Cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 10
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
          show_class_names: true
          link_missing_lines: true
          report_name: code coverage results
  
  benchmarks:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v6
                
      - name: Restore dependencies
        run: |
          dotnet tool restore
          dotnet restore
              
      - name: Publish benchmarks
        run: dotnet publish ./benchmarks/Discorss.Test.Benchmarks/Discorss.Test.Benchmarks.fsproj -c Release -o ./publish/

      - name: Run benchmarks
        run: dotnet ./publish/Discorss.Test.Benchmarks.dll -f "*"

      - name: Archive Benchmark results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: benchmarks.results
          path: |
            ./BenchmarkDotNet.Artifacts/**/results/*.html
    
  build-server-docker-image:
    name: build server docker image
    runs-on: ubuntu-latest
    needs:   [ build, tests, sca, benchmarks ]
    
    steps:
      - uses: actions/checkout@v7
      
      - name: Set Docker image name
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "docker-image-server=${{ env.docker-image-server }}:v${{ env.build-version-number }}" >> $GITHUB_ENV

      - name: Set Preview Docker image name
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "docker-image-server=${{ env.docker-image-server }}:dev" >> $GITHUB_ENV
        
      - name: Build docker image
        run: docker build -f Dockerfile-Service -t ${{ env.docker-image-server }} --build-arg BuildVersion=${{ env.build-version-number }} .

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}

      - name: Push docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: docker push ${{ env.docker-image-server }}

